version: '3.8'

services:
  # Baza danych dla Serwisu Auth (Użytkownicy)
  auth-db:
    image: postgres:15-alpine
    container_name: fitflow-auth-db
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin_password
    ports:
      - "5432:5432"
    volumes:
      - auth_data:/var/lib/postgresql/data
    networks:
      - fitflow-network

  # Baza danych dla Serwisu Operations (Rezerwacje)
  operations-db:
    image: postgres:15-alpine
    container_name: fitflow-ops-db
    environment:
      POSTGRES_DB: operations_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin_password
    ports:
      - "5433:5432" # Zmapowane na port 5433, żeby nie gryzło się z auth-db
    volumes:
      - operations_data:/var/lib/postgresql/data
    networks:
      - fitflow-network

networks:
  fitflow-network:
    driver: bridge

volumes:
  auth_data:
  operations_data: